-- Ken Wheeler
-- Alan Wan
-- Group 22
-- CS 340 Project Step 5

-- MySQL Script generated by MySQL Workbench
-- Tue Oct 28 01:07:51 2025 - Updated 11/22/25 to leverage AUTO INCREMENT via subqueries instead of hard coding PKs and FKs
-- Model: New Model    Version:2.0
-- MySQL Workbench Forward Engineering

USE cs340_wanala;

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
SET AUTOCOMMIT = 0;

-- Drop order: dependent tables first
DROP TABLE IF EXISTS TUITION;
DROP TABLE IF EXISTS UNIVERSITIES_HAS_ATHLETICS;
DROP TABLE IF EXISTS UNIVERSITIES_HAS_MAJORS;
DROP TABLE IF EXISTS ATHLETICS;
DROP TABLE IF EXISTS MAJORS;
DROP TABLE IF EXISTS COSTS;
DROP TABLE IF EXISTS UNIVERSITIES;

-- -----------------------------------------------------
-- Table UNIVERSITIES
-- -----------------------------------------------------
CREATE TABLE UNIVERSITIES (
  universityID INT NOT NULL AUTO_INCREMENT,
  universityName VARCHAR(50) NOT NULL,
  location VARCHAR(50) NOT NULL,
  campusType ENUM('Urban','Suburban','Rural') NOT NULL,
  acceptanceRate DECIMAL(5,2) NOT NULL,
  athleticClassification ENUM('NCAA Division I','NCAA Division II','NCAA Division III','NAIA') NOT NULL,
  PRIMARY KEY (universityID)
) ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table COSTS
-- -----------------------------------------------------
CREATE TABLE COSTS (
  costID INT NOT NULL AUTO_INCREMENT,
  fees DECIMAL(7,2) NOT NULL,
  boarding DECIMAL(7,2) NOT NULL,
  meals DECIMAL(7,2) NOT NULL,
  books DECIMAL(6,2) NOT NULL,
  universityID INT NOT NULL,
  PRIMARY KEY (costID),
  INDEX idx_costs_universityID (universityID),
  CONSTRAINT fk_costs_university
    FOREIGN KEY (universityID)
    REFERENCES UNIVERSITIES (universityID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table ATHLETICS
-- -----------------------------------------------------
CREATE TABLE ATHLETICS (
  sportID INT NOT NULL AUTO_INCREMENT,
  sportName VARCHAR(50) NOT NULL,
  sportType ENUM('Individual','Team') NOT NULL,
  PRIMARY KEY (sportID)
) ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table MAJORS
-- -----------------------------------------------------
CREATE TABLE MAJORS (
  majorID INT NOT NULL AUTO_INCREMENT,
  level ENUM('Undergraduate','Graduate','Certificate') NOT NULL,
  program VARCHAR(50) NOT NULL,
  PRIMARY KEY (majorID)
) ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table UNIVERSITIES_HAS_MAJORS
-- -----------------------------------------------------
CREATE TABLE UNIVERSITIES_HAS_MAJORS (
  universityHasMajorsID INT NOT NULL AUTO_INCREMENT,
  universityID INT NOT NULL,
  majorID INT NOT NULL,
  PRIMARY KEY (universityHasMajorsID),
  INDEX idx_uhm_universityID (universityID),
  INDEX idx_uhm_majorID (majorID),
  CONSTRAINT fk_uhm_university
    FOREIGN KEY (universityID)
    REFERENCES UNIVERSITIES (universityID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_uhm_major
    FOREIGN KEY (majorID)
    REFERENCES MAJORS (majorID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table UNIVERSITIES_HAS_ATHLETICS
-- -----------------------------------------------------
CREATE TABLE UNIVERSITIES_HAS_ATHLETICS (
  universityHasAthleticsID INT NOT NULL AUTO_INCREMENT,
  universityID INT NOT NULL,
  sportID INT NOT NULL,
  PRIMARY KEY (universityHasAthleticsID),
  INDEX idx_uha_universityID (universityID),
  INDEX idx_uha_sportID (sportID),
  CONSTRAINT fk_uha_university
    FOREIGN KEY (universityID)
    REFERENCES UNIVERSITIES (universityID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_uha_sport
    FOREIGN KEY (sportID)
    REFERENCES ATHLETICS (sportID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table TUITION
-- -----------------------------------------------------
CREATE TABLE TUITION (
  tuitionID INT NOT NULL AUTO_INCREMENT,
  currentInStateTuition DECIMAL(8,2) NOT NULL,
  currentOutOfStateTuition DECIMAL(8,2) NOT NULL,
  costID INT NOT NULL,
  PRIMARY KEY (tuitionID),
  CONSTRAINT fk_tuition_costs
    FOREIGN KEY (costID)
    REFERENCES COSTS (costID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB;

INSERT INTO UNIVERSITIES
(universityName, location, campusType, acceptanceRate, athleticClassification)
VALUES
('Oregon State University', 'Corvallis, OR', 'Suburban', 79.00, 'NCAA Division I'),
('University of California, Los Angeles', 'Los Angeles, CA', 'Urban', 9.00, 'NCAA Division I'),
('Washington University in St. Louis', 'St. Louis, MO', 'Suburban', 11.00, 'NCAA Division III'),
('New York University', 'New York, NY', 'Urban', 13.00, 'NCAA Division III'),
('Howard University', 'Washington, DC', 'Urban', 35.00, 'NCAA Division I'),
('Florida A&M University', 'Tallahassee, FL', 'Urban', 33.00, 'NCAA Division I'),
('Dartmouth College', 'Hanover, NH', 'Rural', 6.00, 'NCAA Division I');
 

INSERT INTO COSTS (fees, boarding, meals, books, universityID)
VALUES
(2300.00, 13200.00, 6400.00, 1200.00,
   (SELECT universityID FROM UNIVERSITIES WHERE universityName='Oregon State University')),
(1500.00, 17600.00, 6900.00, 1641.00,
   (SELECT universityID FROM UNIVERSITIES WHERE universityName='University of California, Los Angeles')),
(1350.00, 14500.00, 7700.00, 1304.00,
   (SELECT universityID FROM UNIVERSITIES WHERE universityName='Washington University in St. Louis')),
(2000.00, 18200.00, 7600.00, 1470.00,
   (SELECT universityID FROM UNIVERSITIES WHERE universityName='New York University')),
(1900.00, 14200.00, 6660.00, 1360.00,
   (SELECT universityID FROM UNIVERSITIES WHERE universityName='Howard University')),
(1200.00, 18100.00, 6400.00, 1138.00,
   (SELECT universityID FROM UNIVERSITIES WHERE universityName='Florida A&M University')),
(2318.00, 12579.00, 8341.00, 1005.00,
   (SELECT universityID FROM UNIVERSITIES WHERE universityName='Dartmouth College'));

INSERT INTO TUITION (currentInStateTuition, currentOutOfStateTuition, costID)
VALUES
(15246.00, 33798.00,
   (SELECT costID FROM COSTS WHERE universityID = 
       (SELECT universityID FROM UNIVERSITIES WHERE universityName='Oregon State University'))),
(15700.00, 37602.00,
   (SELECT costID FROM COSTS WHERE universityID = 
       (SELECT universityID FROM UNIVERSITIES WHERE universityName='University of California, Los Angeles'))),
(68240.00, 68240.00,
   (SELECT costID FROM COSTS WHERE universityID = 
       (SELECT universityID FROM UNIVERSITIES WHERE universityName='Washington University in St. Louis'))),
(62796.00, 62796.00,
   (SELECT costID FROM COSTS WHERE universityID = 
       (SELECT universityID FROM UNIVERSITIES WHERE universityName='New York University'))),
(37996.00, 37996.00,
   (SELECT costID FROM COSTS WHERE universityID = 
       (SELECT universityID FROM UNIVERSITIES WHERE universityName='Howard University'))),
(5697.30, 17585.40,
   (SELECT costID FROM COSTS WHERE universityID = 
       (SELECT universityID FROM UNIVERSITIES WHERE universityName='Florida A&M University'))),
(69207.00, 69207.00,
   (SELECT costID FROM COSTS WHERE universityID = 
       (SELECT universityID FROM UNIVERSITIES WHERE universityName='Dartmouth College')));


-- sportID mapping
 
-- 1  = Football (Men)            | Team
-- 2  = Basketball (Men)          | Team
-- 3  = Basketball (Women)        | Team
-- 4  = Track and Field (Men)     | Individual
-- 5  = Track and Field (Women)   | Individual
-- 6  = Soccer (Men)              | Team
-- 7  = Soccer (Women)            | Team
-- 8  = Swimming (Men)            | Individual
-- 9  = Swimming (Women)          | Individual
-- 10 = Swimming (Coed)           | Individual


INSERT INTO ATHLETICS (sportName, sportType)
VALUES
('Football (Men)', 'Team'),
('Basketball (Men)', 'Team'),
('Basketball (Women)', 'Team'),
('Track and Field (Men)', 'Individual'),
('Track and Field (Women)', 'Individual'),
('Soccer (Men)', 'Team'),
('Soccer (Women)', 'Team'),
('Swimming (Men)', 'Individual'),
('Swimming (Women)', 'Individual'),
('Swimming (Coed)', 'Individual');


 
-- majorID mapping

-- 1  = Undergraduate | Computer Science
-- 2  = Undergraduate | Business Administration
-- 3  = Graduate      | Public Health
-- 4  = Graduate      | Mechanical Engineering
-- 5  = Undergraduate | Psychology

INSERT INTO MAJORS
(level, program)
VALUES
('Undergraduate', 'Computer Science'),
('Undergraduate', 'Business Administration'),
('Graduate', 'Public Health'),
('Graduate', 'Mechanical Engineering'),
('Undergraduate', 'Psychology');


INSERT INTO UNIVERSITIES_HAS_MAJORS (universityID, majorID)
VALUES
((SELECT universityID FROM UNIVERSITIES WHERE universityName='Oregon State University'),
 (SELECT majorID FROM MAJORS WHERE program='Computer Science' AND level='Undergraduate')),

((SELECT universityID FROM UNIVERSITIES WHERE universityName='Oregon State University'),
 (SELECT majorID FROM MAJORS WHERE program='Business Administration' AND level='Undergraduate')),

((SELECT universityID FROM UNIVERSITIES WHERE universityName='University of California, Los Angeles'),
 (SELECT majorID FROM MAJORS WHERE program='Computer Science' AND level='Undergraduate')),

((SELECT universityID FROM UNIVERSITIES WHERE universityName='University of California, Los Angeles'),
 (SELECT majorID FROM MAJORS WHERE program='Psychology' AND level='Undergraduate')),

((SELECT universityID FROM UNIVERSITIES WHERE universityName='Washington University in St. Louis'),
 (SELECT majorID FROM MAJORS WHERE program='Mechanical Engineering' AND level='Graduate')),

((SELECT universityID FROM UNIVERSITIES WHERE universityName='Washington University in St. Louis'),
 (SELECT majorID FROM MAJORS WHERE program='Public Health' AND level='Graduate')),

((SELECT universityID FROM UNIVERSITIES WHERE universityName='New York University'),
 (SELECT majorID FROM MAJORS WHERE program='Business Administration' AND level='Undergraduate')),

((SELECT universityID FROM UNIVERSITIES WHERE universityName='New York University'),
 (SELECT majorID FROM MAJORS WHERE program='Psychology' AND level='Undergraduate')),

((SELECT universityID FROM UNIVERSITIES WHERE universityName='Howard University'),
 (SELECT majorID FROM MAJORS WHERE program='Public Health' AND level='Graduate')),

((SELECT universityID FROM UNIVERSITIES WHERE universityName='Florida A&M University'),
 (SELECT majorID FROM MAJORS WHERE program='Computer Science' AND level='Undergraduate')),

((SELECT universityID FROM UNIVERSITIES WHERE universityName='Dartmouth College'),
 (SELECT majorID FROM MAJORS WHERE program='Computer Science' AND level='Undergraduate')),

((SELECT universityID FROM UNIVERSITIES WHERE universityName='Dartmouth College'),
 (SELECT majorID FROM MAJORS WHERE program='Psychology' AND level='Undergraduate')),

((SELECT universityID FROM UNIVERSITIES WHERE universityName='Dartmouth College'),
 (SELECT majorID FROM MAJORS WHERE program='Mechanical Engineering' AND level='Graduate'));


-- Oregon State University (OSU)
INSERT INTO UNIVERSITIES_HAS_ATHLETICS (universityID, sportID) 
VALUES
((SELECT universityID FROM UNIVERSITIES WHERE universityName='Oregon State University'),
 (SELECT sportID FROM ATHLETICS WHERE sportName='Football (Men)')),
((SELECT universityID FROM UNIVERSITIES WHERE universityName='Oregon State University'),
 (SELECT sportID FROM ATHLETICS WHERE sportName='Basketball (Men)')),
((SELECT universityID FROM UNIVERSITIES WHERE universityName='Oregon State University'),
 (SELECT sportID FROM ATHLETICS WHERE sportName='Track and Field (Men)')),
((SELECT universityID FROM UNIVERSITIES WHERE universityName='Oregon State University'),
 (SELECT sportID FROM ATHLETICS WHERE sportName='Soccer (Men)')),
((SELECT universityID FROM UNIVERSITIES WHERE universityName='Oregon State University'),
 (SELECT sportID FROM ATHLETICS WHERE sportName='Swimming (Men)'));


-- UCLA
INSERT INTO UNIVERSITIES_HAS_ATHLETICS (universityID, sportID) 
VALUES
((SELECT universityID FROM UNIVERSITIES WHERE universityName='University of California, Los Angeles'),
 (SELECT sportID FROM ATHLETICS WHERE sportName='Basketball (Men)')),
((SELECT universityID FROM UNIVERSITIES WHERE universityName='University of California, Los Angeles'),
 (SELECT sportID FROM ATHLETICS WHERE sportName='Basketball (Women)')),
((SELECT universityID FROM UNIVERSITIES WHERE universityName='University of California, Los Angeles'),
 (SELECT sportID FROM ATHLETICS WHERE sportName='Soccer (Women)')),
((SELECT universityID FROM UNIVERSITIES WHERE universityName='University of California, Los Angeles'),
 (SELECT sportID FROM ATHLETICS WHERE sportName='Swimming (Women)')),
((SELECT universityID FROM UNIVERSITIES WHERE universityName='University of California, Los Angeles'),
 (SELECT sportID FROM ATHLETICS WHERE sportName='Track and Field (Women)'));


-- Washington University
INSERT INTO UNIVERSITIES_HAS_ATHLETICS (universityID, sportID) 
VALUES
((SELECT universityID FROM UNIVERSITIES WHERE universityName='Washington University in St. Louis'),
 (SELECT sportID FROM ATHLETICS WHERE sportName='Football (Men)')),
((SELECT universityID FROM UNIVERSITIES WHERE universityName='Washington University in St. Louis'),
 (SELECT sportID FROM ATHLETICS WHERE sportName='Basketball (Women)')),
((SELECT universityID FROM UNIVERSITIES WHERE universityName='Washington University in St. Louis'),
 (SELECT sportID FROM ATHLETICS WHERE sportName='Swimming (Coed)')),
((SELECT universityID FROM UNIVERSITIES WHERE universityName='Washington University in St. Louis'),
 (SELECT sportID FROM ATHLETICS WHERE sportName='Track and Field (Men)')),
((SELECT universityID FROM UNIVERSITIES WHERE universityName='Washington University in St. Louis'),
 (SELECT sportID FROM ATHLETICS WHERE sportName='Soccer (Women)'));

-- New York University (NYU)
INSERT INTO UNIVERSITIES_HAS_ATHLETICS (universityID, sportID) 
VALUES
((SELECT universityID FROM UNIVERSITIES WHERE universityName='New York University'),
 (SELECT sportID FROM ATHLETICS WHERE sportName='Basketball (Men)')),
((SELECT universityID FROM UNIVERSITIES WHERE universityName='New York University'),
 (SELECT sportID FROM ATHLETICS WHERE sportName='Swimming (Coed)')),
((SELECT universityID FROM UNIVERSITIES WHERE universityName='New York University'),
 (SELECT sportID FROM ATHLETICS WHERE sportName='Track and Field (Women)')),
((SELECT universityID FROM UNIVERSITIES WHERE universityName='New York University'),
 (SELECT sportID FROM ATHLETICS WHERE sportName='Soccer (Men)')),
((SELECT universityID FROM UNIVERSITIES WHERE universityName='New York University'),
 (SELECT sportID FROM ATHLETICS WHERE sportName='Swimming (Men)'));
;


-- Howard University
INSERT INTO UNIVERSITIES_HAS_ATHLETICS (universityID, sportID) 
VALUES
((SELECT universityID FROM UNIVERSITIES WHERE universityName='Howard University'),
 (SELECT sportID FROM ATHLETICS WHERE sportName='Football (Men)')),
((SELECT universityID FROM UNIVERSITIES WHERE universityName='Howard University'),
 (SELECT sportID FROM ATHLETICS WHERE sportName='Basketball (Men)')),
((SELECT universityID FROM UNIVERSITIES WHERE universityName='Howard University'),
 (SELECT sportID FROM ATHLETICS WHERE sportName='Basketball (Women)')),
((SELECT universityID FROM UNIVERSITIES WHERE universityName='Howard University'),
 (SELECT sportID FROM ATHLETICS WHERE sportName='Track and Field (Women)')),
((SELECT universityID FROM UNIVERSITIES WHERE universityName='Howard University'),
 (SELECT sportID FROM ATHLETICS WHERE sportName='Swimming (Women)'));


-- Florida A&M University (FAMU)
INSERT INTO UNIVERSITIES_HAS_ATHLETICS (universityID, sportID) 
VALUES
((SELECT universityID FROM UNIVERSITIES WHERE universityName='Florida A&M University'),
 (SELECT sportID FROM ATHLETICS WHERE sportName='Football (Men)')),
((SELECT universityID FROM UNIVERSITIES WHERE universityName='Florida A&M University'),
 (SELECT sportID FROM ATHLETICS WHERE sportName='Soccer (Men)')),
((SELECT universityID FROM UNIVERSITIES WHERE universityName='Florida A&M University'),
 (SELECT sportID FROM ATHLETICS WHERE sportName='Soccer (Women)')),
((SELECT universityID FROM UNIVERSITIES WHERE universityName='Florida A&M University'),
 (SELECT sportID FROM ATHLETICS WHERE sportName='Track and Field (Men)')),
((SELECT universityID FROM UNIVERSITIES WHERE universityName='Florida A&M University'),
 (SELECT sportID FROM ATHLETICS WHERE sportName='Swimming (Coed)'));

-- Dartmouth College
INSERT INTO UNIVERSITIES_HAS_ATHLETICS (universityID, sportID) 
VALUES
((SELECT universityID FROM UNIVERSITIES WHERE universityName='Dartmouth College'),
 (SELECT sportID FROM ATHLETICS WHERE sportName='Basketball (Men)')),
((SELECT universityID FROM UNIVERSITIES WHERE universityName='Dartmouth College'),
 (SELECT sportID FROM ATHLETICS WHERE sportName='Track and Field (Men)')),
((SELECT universityID FROM UNIVERSITIES WHERE universityName='Dartmouth College'),
 (SELECT sportID FROM ATHLETICS WHERE sportName='Track and Field (Women)')),
((SELECT universityID FROM UNIVERSITIES WHERE universityName='Dartmouth College'),
 (SELECT sportID FROM ATHLETICS WHERE sportName='Swimming (Men)')),
((SELECT universityID FROM UNIVERSITIES WHERE universityName='Dartmouth College'),
 (SELECT sportID FROM ATHLETICS WHERE sportName='Soccer (Women)'));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=1;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
COMMIT;